name: GitOps Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-apply:
    name: Apply Terraform Changes (GitOps)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Project_18

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Plan
        run: terraform plan -out=tfplan.out

      - name: Terraform Apply (auto-approve)
        run: terraform apply -auto-approve tfplan.out
